DROP DATABASE IF EXISTS shop;
create database shop;
use shop;
create table user (id INT NOT NULL AUTO_INCREMENT, email VARCHAR(30) NOT NULL, hash_password VARCHAR(100) NOT NULL, name VARCHAR(50) NOT NULL,  region VARCHAR(30) NOT NULL, role ENUM('admin', 'user'), PRIMARY KEY (id));
create table booking (id INT NOT NULL AUTO_INCREMENT, id_user INT NOT NULL, id_furniture INT NOT NULL, category VARCHAR(30) NOT NULL, PRIMARY KEY (id));
create table mattress (id INT NOT NULL AUTO_INCREMENT, price int not null, brand varchar(30) not null, kind varchar(30) not null, max_weight int not null,  PRIMARY KEY (id));
create table bed (id INT NOT NULL AUTO_INCREMENT, price int not null, brand varchar(30) not null, wood_variety varchar(30) not null, size varchar(30) not null,  PRIMARY KEY (id));
create table sofa (id INT NOT NULL AUTO_INCREMENT, price int not null, brand varchar(30) not null, armrest ENUM('wood', 'soft', 'without'), num_of_seats int not null, description VARCHAR(2000),  PRIMARY KEY (id));

show tables;
SELECT * FROM sofa;

# password - 1234
insert INTO user(email, hash_password, name, region, role) VALUES ('admin@admin.com', '$2a$10$5RhehnDP.gL2W5sYP9vcdu8G0k63Lj9zWri6bBlrZHQ0hDZiiMsOS',	'Natasha',	'Poznan',	'admin');


insert INTO bed(price, brand, wood_variety, size) VALUES (50, 'IKEA', 'good', 'big');
insert INTO bed(price, brand, wood_variety, size) VALUES (60, 'MOON', 'bad', 'small');
insert INTO bed(price, brand, wood_variety, size) VALUES (70, 'LOOL', 'middle', 'middle');
insert INTO bed(price, brand, wood_variety, size) VALUES (30, 'IKEA', 'very-very', 'small');
insert INTO bed(price, brand, wood_variety, size) VALUES (66, 'EST', 'good', 'big');
insert INTO bed(price, brand, wood_variety, size) VALUES (54, 'POL', 'good', 'middle');
insert INTO bed(price, brand, wood_variety, size) VALUES (34, 'POZ', 'bad', 'big');
insert INTO bed(price, brand, wood_variety, size) VALUES (66, 'POZ', 'good', 'small');
insert INTO bed(price, brand, wood_variety, size) VALUES (123, 'EST', 'bad', 'big');
insert INTO bed(price, brand, wood_variety, size) VALUES (555, 'IKEA', 'good', 'big');
insert INTO bed(price, brand, wood_variety, size) VALUES (122, 'IKEA', 'good', 'middle');
insert INTO bed(price, brand, wood_variety, size) VALUES (123, 'IKEA', 'amazing', 'big');
insert INTO bed(price, brand, wood_variety, size) VALUES (512, 'MOON', 'good', 'big');
insert INTO bed(price, brand, wood_variety, size) VALUES (12, 'IKEA', 'cool', 'small');

insert INTO mattress(price, brand, kind, max_weight) VALUES (40, 'IKEA', 'kind', 122);
insert INTO mattress(price, brand, kind, max_weight) VALUES (50, 'IKEA', 'bad', 200);
insert INTO mattress(price, brand, kind, max_weight) VALUES (20, 'MOON', 'good', 122);
insert INTO mattress(price, brand, kind, max_weight) VALUES (430, 'IKEA', 'kind', 122);
insert INTO mattress(price, brand, kind, max_weight) VALUES (455, 'IKEA', 'kind', 300);
insert INTO mattress(price, brand, kind, max_weight) VALUES (56, 'BAD', 'kind', 300);
insert INTO mattress(price, brand, kind, max_weight) VALUES (123, 'IKEA', 'type', 444);
insert INTO mattress(price, brand, kind, max_weight) VALUES (40, 'EST', 'kind', 122);
insert INTO mattress(price, brand, kind, max_weight) VALUES (40, 'IKEA', 'kind', 122);
insert INTO mattress(price, brand, kind, max_weight) VALUES (123, 'POZ', 'idea', 50);
insert INTO mattress(price, brand, kind, max_weight) VALUES (40, 'IKEA', 'kind', 122);
insert INTO mattress(price, brand, kind, max_weight) VALUES (66, 'POL', 'kind', 30);
insert INTO mattress(price, brand, kind, max_weight) VALUES (40, 'POL', 'lol', 122);
insert INTO mattress(price, brand, kind, max_weight) VALUES (434, 'POL', 'kind', 234);
insert INTO mattress(price, brand, kind, max_weight) VALUES (120, 'IKEA', 'bb', 122);
insert INTO mattress(price, brand, kind, max_weight) VALUES (430, 'POZ', 'kind', 3333);
insert INTO mattress(price, brand, kind, max_weight) VALUES (40, 'IKEA', 'kind', 66);
insert INTO mattress(price, brand, kind, max_weight) VALUES (4120, 'POZ', 'sdf', 120);
insert INTO mattress(price, brand, kind, max_weight) VALUES (403, 'IKEA', 'kind', 122);

insert INTO sofa (price, brand, armrest, num_of_seats, description) VALUES (422, 'Sofyno','wood', 2,'Even though you don''t see the sofa''s structure, it forms the basis of how comfortable the sofa is for the user. A comfortable sofa has a frame designed in such a way that it''s easy to get up and down from the seated position. The frame needs to be sturdy enough to support the weight of several people. Look for sofa frames constructed of hardwood, such as kiln-dried ash, oak or beech. Examine the legs of the sofa. They should either be part of the frame itself or attached with dowels or screws. If you raise one of the front corners of a sofa, the other front leg should come off the floor as well, if the sofa has a solid structure. If the other leg doesn''t rise from the floor, the sofa is structurally weak and may not be comfortable over time.' );
insert INTO sofa (price, brand, armrest, num_of_seats, description) VALUES (123, 'IKEA','soft', 2, 'Even though you don''t see the sofa''s structure, it forms the basis of how comfortable the sofa is for the user. A comfortable sofa has a frame designed in such a way that it''s easy to get up and down from the seated position. The frame needs to be sturdy enough to support the weight of several people. Look for sofa frames constructed of hardwood, such as kiln-dried ash, oak or beech. Examine the legs of the sofa. They should either be part of the frame itself or attached with dowels or screws. If you raise one of the front corners of a sofa, the other front leg should come off the floor as well, if the sofa has a solid structure. If the other leg doesn''t rise from the floor, the sofa is structurally weak and may not be comfortable over time.');
insert INTO sofa (price, brand, armrest, num_of_seats, description) VALUES (422, 'SkySoft','wood', 3, 'Even though you don''t see the sofa''s structure, it forms the basis of how comfortable the sofa is for the user. A comfortable sofa has a frame designed in such a way that it''s easy to get up and down from the seated position. The frame needs to be sturdy enough to support the weight of several people. Look for sofa frames constructed of hardwood, such as kiln-dried ash, oak or beech. Examine the legs of the sofa. They should either be part of the frame itself or attached with dowels or screws. If you raise one of the front corners of a sofa, the other front leg should come off the floor as well, if the sofa has a solid structure. If the other leg doesn''t rise from the floor, the sofa is structurally weak and may not be comfortable over time.');
insert INTO sofa (price, brand, armrest, num_of_seats, description) VALUES (123, 'IKEA','without', 3, 'Even though you don''t see the sofa''s structure, it forms the basis of how comfortable the sofa is for the user. A comfortable sofa has a frame designed in such a way that it''s easy to get up and down from the seated position. The frame needs to be sturdy enough to support the weight of several people. Look for sofa frames constructed of hardwood, such as kiln-dried ash, oak or beech. Examine the legs of the sofa. They should either be part of the frame itself or attached with dowels or screws. If you raise one of the front corners of a sofa, the other front leg should come off the floor as well, if the sofa has a solid structure. If the other leg doesn''t rise from the floor, the sofa is structurally weak and may not be comfortable over time.');
insert INTO sofa (price, brand, armrest, num_of_seats, description) VALUES (422, 'SkySoft','soft', 4, 'Even though you don''t see the sofa''s structure, it forms the basis of how comfortable the sofa is for the user. A comfortable sofa has a frame designed in such a way that it''s easy to get up and down from the seated position. The frame needs to be sturdy enough to support the weight of several people. Look for sofa frames constructed of hardwood, such as kiln-dried ash, oak or beech. Examine the legs of the sofa. They should either be part of the frame itself or attached with dowels or screws. If you raise one of the front corners of a sofa, the other front leg should come off the floor as well, if the sofa has a solid structure. If the other leg doesn''t rise from the floor, the sofa is structurally weak and may not be comfortable over time.');
insert INTO sofa (price, brand, armrest, num_of_seats, description) VALUES (443, 'IKEA','wood', 2, 'Even though you don''t see the sofa''s structure, it forms the basis of how comfortable the sofa is for the user. A comfortable sofa has a frame designed in such a way that it''s easy to get up and down from the seated position. The frame needs to be sturdy enough to support the weight of several people. Look for sofa frames constructed of hardwood, such as kiln-dried ash, oak or beech. Examine the legs of the sofa. They should either be part of the frame itself or attached with dowels or screws. If you raise one of the front corners of a sofa, the other front leg should come off the floor as well, if the sofa has a solid structure. If the other leg doesn''t rise from the floor, the sofa is structurally weak and may not be comfortable over time.');
insert INTO sofa (price, brand, armrest, num_of_seats, description) VALUES (422, 'Laretto','wood', 2, 'Even though you don''t see the sofa''s structure, it forms the basis of how comfortable the sofa is for the user. A comfortable sofa has a frame designed in such a way that it''s easy to get up and down from the seated position. The frame needs to be sturdy enough to support the weight of several people. Look for sofa frames constructed of hardwood, such as kiln-dried ash, oak or beech. Examine the legs of the sofa. They should either be part of the frame itself or attached with dowels or screws. If you raise one of the front corners of a sofa, the other front leg should come off the floor as well, if the sofa has a solid structure. If the other leg doesn''t rise from the floor, the sofa is structurally weak and may not be comfortable over time.');
insert INTO sofa (price, brand, armrest, num_of_seats, description) VALUES (34, 'Laretto','soft', 3, 'Even though you don''t see the sofa''s structure, it forms the basis of how comfortable the sofa is for the user. A comfortable sofa has a frame designed in such a way that it''s easy to get up and down from the seated position. The frame needs to be sturdy enough to support the weight of several people. Look for sofa frames constructed of hardwood, such as kiln-dried ash, oak or beech. Examine the legs of the sofa. They should either be part of the frame itself or attached with dowels or screws. If you raise one of the front corners of a sofa, the other front leg should come off the floor as well, if the sofa has a solid structure. If the other leg doesn''t rise from the floor, the sofa is structurally weak and may not be comfortable over time.');
insert INTO sofa (price, brand, armrest, num_of_seats, description) VALUES (422, 'IKEA','without', 2, 'Even though you don''t see the sofa''s structure, it forms the basis of how comfortable the sofa is for the user. A comfortable sofa has a frame designed in such a way that it''s easy to get up and down from the seated position. The frame needs to be sturdy enough to support the weight of several people. Look for sofa frames constructed of hardwood, such as kiln-dried ash, oak or beech. Examine the legs of the sofa. They should either be part of the frame itself or attached with dowels or screws. If you raise one of the front corners of a sofa, the other front leg should come off the floor as well, if the sofa has a solid structure. If the other leg doesn''t rise from the floor, the sofa is structurally weak and may not be comfortable over time.');
insert INTO sofa (price, brand, armrest, num_of_seats, description) VALUES (422, 'BRAND','without', 8, 'Even though you don''t see the sofa''s structure, it forms the basis of how comfortable the sofa is for the user. A comfortable sofa has a frame designed in such a way that it''s easy to get up and down from the seated position. The frame needs to be sturdy enough to support the weight of several people. Look for sofa frames constructed of hardwood, such as kiln-dried ash, oak or beech. Examine the legs of the sofa. They should either be part of the frame itself or attached with dowels or screws. If you raise one of the front corners of a sofa, the other front leg should come off the floor as well, if the sofa has a solid structure. If the other leg doesn''t rise from the floor, the sofa is structurally weak and may not be comfortable over time.');
insert INTO sofa (price, brand, armrest, num_of_seats, description) VALUES (223, 'IKEA','soft', 4, 'Even though you don''t see the sofa''s structure, it forms the basis of how comfortable the sofa is for the user. A comfortable sofa has a frame designed in such a way that it''s easy to get up and down from the seated position. The frame needs to be sturdy enough to support the weight of several people. Look for sofa frames constructed of hardwood, such as kiln-dried ash, oak or beech. Examine the legs of the sofa. They should either be part of the frame itself or attached with dowels or screws. If you raise one of the front corners of a sofa, the other front leg should come off the floor as well, if the sofa has a solid structure. If the other leg doesn''t rise from the floor, the sofa is structurally weak and may not be comfortable over time.');
insert INTO sofa (price, brand, armrest, num_of_seats, description) VALUES (223, 'DivanPlus','soft', 2, 'Even though you don''t see the sofa''s structure, it forms the basis of how comfortable the sofa is for the user. A comfortable sofa has a frame designed in such a way that it''s easy to get up and down from the seated position. The frame needs to be sturdy enough to support the weight of several people. Look for sofa frames constructed of hardwood, such as kiln-dried ash, oak or beech. Examine the legs of the sofa. They should either be part of the frame itself or attached with dowels or screws. If you raise one of the front corners of a sofa, the other front leg should come off the floor as well, if the sofa has a solid structure. If the other leg doesn''t rise from the floor, the sofa is structurally weak and may not be comfortable over time.');
insert INTO sofa (price, brand, armrest, num_of_seats, description) VALUES (422, 'IKEA','soft', 2, 'Even though you don''t see the sofa''s structure, it forms the basis of how comfortable the sofa is for the user. A comfortable sofa has a frame designed in such a way that it''s easy to get up and down from the seated position. The frame needs to be sturdy enough to support the weight of several people. Look for sofa frames constructed of hardwood, such as kiln-dried ash, oak or beech. Examine the legs of the sofa. They should either be part of the frame itself or attached with dowels or screws. If you raise one of the front corners of a sofa, the other front leg should come off the floor as well, if the sofa has a solid structure. If the other leg doesn''t rise from the floor, the sofa is structurally weak and may not be comfortable over time.');
insert INTO sofa (price, brand, armrest, num_of_seats, description) VALUES (2, 'DivanPlus','wood', 3, 'Even though you don''t see the sofa''s structure, it forms the basis of how comfortable the sofa is for the user. A comfortable sofa has a frame designed in such a way that it''s easy to get up and down from the seated position. The frame needs to be sturdy enough to support the weight of several people. Look for sofa frames constructed of hardwood, such as kiln-dried ash, oak or beech. Examine the legs of the sofa. They should either be part of the frame itself or attached with dowels or screws. If you raise one of the front corners of a sofa, the other front leg should come off the floor as well, if the sofa has a solid structure. If the other leg doesn''t rise from the floor, the sofa is structurally weak and may not be comfortable over time.');
insert INTO sofa (price, brand, armrest, num_of_seats, description) VALUES (22, 'IKEA','wood', 2, 'Even though you don''t see the sofa''s structure, it forms the basis of how comfortable the sofa is for the user. A comfortable sofa has a frame designed in such a way that it''s easy to get up and down from the seated position. The frame needs to be sturdy enough to support the weight of several people. Look for sofa frames constructed of hardwood, such as kiln-dried ash, oak or beech. Examine the legs of the sofa. They should either be part of the frame itself or attached with dowels or screws. If you raise one of the front corners of a sofa, the other front leg should come off the floor as well, if the sofa has a solid structure. If the other leg doesn''t rise from the floor, the sofa is structurally weak and may not be comfortable over time.');
insert INTO sofa (price, brand, armrest, num_of_seats, description) VALUES (422, 'SkySoft','without', 2, 'Even though you don''t see the sofa''s structure, it forms the basis of how comfortable the sofa is for the user. A comfortable sofa has a frame designed in such a way that it''s easy to get up and down from the seated position. The frame needs to be sturdy enough to support the weight of several people. Look for sofa frames constructed of hardwood, such as kiln-dried ash, oak or beech. Examine the legs of the sofa. They should either be part of the frame itself or attached with dowels or screws. If you raise one of the front corners of a sofa, the other front leg should come off the floor as well, if the sofa has a solid structure. If the other leg doesn''t rise from the floor, the sofa is structurally weak and may not be comfortable over time.');
insert INTO sofa (price, brand, armrest, num_of_seats, description) VALUES (56, 'Sofyno','without', 2, 'Even though you don''t see the sofa''s structure, it forms the basis of how comfortable the sofa is for the user. A comfortable sofa has a frame designed in such a way that it''s easy to get up and down from the seated position. The frame needs to be sturdy enough to support the weight of several people. Look for sofa frames constructed of hardwood, such as kiln-dried ash, oak or beech. Examine the legs of the sofa. They should either be part of the frame itself or attached with dowels or screws. If you raise one of the front corners of a sofa, the other front leg should come off the floor as well, if the sofa has a solid structure. If the other leg doesn''t rise from the floor, the sofa is structurally weak and may not be comfortable over time.');
